osx_image: xcode8.3
language: objective-c
cache:
  - bundler
  - cocoapods

podfile: ios/analytics/Podfile
env: SAMPLE=Analytics

matrix:
  include:
  - podfile: ios/signin/Podfile
    env: SAMPLE=SignIn

rvm: 2.3.1
before_install:
  - open -a "simulator" --args -CurrentDeviceUDID F60B87EC-8969-41A7-90ED-D0826ECC32DB
  - cd ios/$SAMPLE
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --repo-update
  - sed -i '' 's/YOUR_REVERSED_CLIENT_ID/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/' "$SAMPLE"Example/Info.plist
  - cd -

script: ios/test.sh
